// react-frontend/src/components/Objects.js
import React from 'react';
import { FolderIcon, FolderOpenIcon, DocumentIcon } from '@heroicons/react/solid';
import { useDispatch, useSelector } from 'react-redux';
import { toggleNode } from '../redux/actions'; // Certifique-se de que o caminho está correto
import TreeView from './TreeView';

const Objects = () => {
    const treeData = useSelector((state) => state.treeData);
    const dispatch = useDispatch();

    const handleToggle = (nodeId) => {
        dispatch(toggleNode(nodeId));
    };

    const handleAddFrame = () => {
        const frameName = "New Frame"; // Substitua com a lógica de nomeação desejada
        dispatch(addFrame(frameName));
    };

    const startDrag = (event, node) => {
        event.dataTransfer.setData('nodeData', JSON.stringify(node));
    };

    return (
        <ul className="pl-4 space-y-2">
            <div className="add-tab" onClick={handleAddFrame}>
                +
            </div>
            {treeData.map(node => (
                <li key={node.id}>
                    <div className="flex items-center space-x-2" onClick={() => dispatch(toggleNode(node))}>
                        <span>
                            {node.children && node.children.length > 0 ? (
                                node.expanded ? <FolderOpenIcon className="w-5 h-5 text-yellow-400" /> : <FolderIcon className="w-5 h-5 text-yellow-400" />
                            ) : (
                                <DocumentIcon className="w-5 h-5" onDragStart={(event) => startDrag(event, node)} draggable="true" />
                            )}
                        </span>
                        <span className="text">{node.name}</span>
                    </div>
                    {node.expanded && node.children && <TreeView initialTreeData={node.children} />}
                </li>
            ))}
        </ul>
    );
};

export default Objects;

// frontend/src/components/Objects.vue
<!--Objects.vue-->
<template>
    <ul class="pl-4 space-y-2">
        <li v-for="node in treeData" :key="node.id">
            <div class="flex items-center space-x-2" @click="toggle(node)">
                <span v-if="node.children && node.children.length">
                    <FolderOpenIcon v-if="node.expanded" class="w-5 h-5 text-yellow-400"/>
                    <FolderIcon v-else class="w-5 h-5 text-yellow-400"/>
                </span>
                <span v-else @dragstart="startDrag($event, node)" draggable="true">
                    <DocumentIcon class="w-5 h-5"/>
                </span>
                <span class="text">
                {{ node.name }}
                    </span>
            </div>
            <tree-view v-if="node.expanded && node.children" :tree-data="node.children" />
        </li>
    </ul>
</template>

<script>
import { FolderIcon, FolderOpenIcon, DocumentIcon } from '@heroicons/vue/solid';
import { EventBus } from '../EventBus.js';
export default {
    data() {
        return {
            frames: [] // Supondo que você tenha uma lista de frames
        };
    },
    props: {
        treeData: {
            type: Array,
            default: () => []
        }
    },
    methods: {
        addNewFrame(frameName) {
            this.treeData.push({
                id: this.treeData.length + 1,
                name: frameName,
                expanded: false
            });
        },
        toggle(node) {
            node.expanded = !node.expanded;
        },
        startDrag(event, node) {
            event.dataTransfer.setData('nodeData', JSON.stringify(node));
        },

    },
    created() {
        EventBus.on('add-frame', this.addNewFrame);

    },
    beforeDestroy() {
        EventBus.off('add-frame', this.addNewFrame);
    },
}
</script>
<style scoped>
.project-pane, .structure-pane {
    max-height: 300px; /* Defina a altura máxima que você deseja para os painéis. */
}
</style>
