// react-frontend/src/TreeView.js
import React, { useState } from 'react';
// Importe seus ícones do pacote react-icons ou onde eles estiverem disponíveis.
// Suponha que você tenha ícones equivalentes em React.
import { FolderOpenIcon, FolderIcon, DocumentIcon } from '@heroicons/react/solid';

const TreeView = ({ treeData }) => {
  // Criação de um novo estado para armazenar os dados da árvore com a propriedade 'expanded'
  const [nodes, setNodes] = useState(treeData.map(node => ({ ...node, expanded: false })));

  // Função para alternar a visibilidade dos filhos de um nó
  const toggle = (node) => {
    setNodes(nodes.map(n => {
      if (n.id === node.id) {
        return { ...n, expanded: !n.expanded };
      }
      return n;
    }));
  };

  // Função para iniciar o arraste de um nó
  const startDrag = (event, node) => {
    event.dataTransfer.setData('nodeData', JSON.stringify(node));
  };

  return (
    <ul className="pl-4 space-y-2">
      {nodes.map(node => (
        <li key={node.id}>
          <div className="flex items-center space-x-2" onClick={() => toggle(node)}>
            <span>
              {node.children && node.children.length ? (
                node.expanded ? (
                  // Substitua pelos ícones de pasta aberta e fechada do seu pacote de ícones
                  <FolderOpenIcon className="w-6 h-6 text-yellow-400" />
                ) : (
                  <FolderIcon className="w-6 h-6 text-yellow-400" />
                )
              ) : (
                node.iconClass ? (
                  <div className={`${node.iconClass} nb-icons`} draggable="true" onDragStart={(e) => startDrag(e, node)}></div>
                ) : (
                  <DocumentIcon className="w-6 h-6 text-yellow-400" />
                )
              )}
            </span>
            <span className="text">
              {node.name}
            </span>
          </div>
          {node.expanded && node.children && (
            <TreeView treeData={node.children} />
          )}
        </li>
      ))}
    </ul>
  );
};

export default TreeView;

// frontend/src/components/TreeView.vue
<!--TreeView.vue-->
<template>
    <ul class="pl-4 space-y-2">
        <li v-for="node in treeData" :key="node.id">
            <div class="flex items-center space-x-2" @click="toggle(node)">
              <span>
                <template v-if="node.children && node.children.length">
                  <FolderOpenIcon v-if="node.expanded" class="w-5 h-5 text-yellow-400"/>
                  <FolderIcon v-else class="w-5 h-5 text-yellow-400"/>
                </template>
                <template v-else>
                  <div :class="['nb-icons', node.iconClass]" @dragstart="startDrag($event, node)" draggable="true"></div>
                </template>
              </span>
                <span class="text">
                {{ node.name }}
                    </span>
            </div>
            <tree-view v-if="node.expanded && node.children" :tree-data="node.children" />
        </li>
    </ul>
</template>

<script>
import { FolderIcon, FolderOpenIcon, DocumentIcon } from '@heroicons/vue/solid';

export default {
    name: "TreeView",
    components: {
        FolderIcon,
        FolderOpenIcon,
        DocumentIcon,
        TreeView: "TreeView"
    },
    props: {
        treeData: {
            type: Array,
            default: () => []
        }
    },
    methods: {
        toggle(node) {
            node.expanded = !node.expanded;
        },
        startDrag(event, node) {
            event.dataTransfer.setData('nodeData', JSON.stringify(node));
        }
    }
}
</script>
