// resources/js/components/TabsComponent.vue
<!--TabsComponent.vue-->
<template>
    <div class="tabs-container mt-6">
        <div class="tabs-wrapper flex overflow-x-auto">
            <div v-for="(tab, index) in tabs" :key="tab.id"
                 :class="{'active-tab': activeTab === index}"
                 @click="changeTab(index)"
                 @dblclick="enableEdit(tab)"
                 class="tab inline-flex flex-shrink-0 px-6 py-2 mr-1 rounded-t-lg cursor-pointer">
                <input v-if="tab.isEditing" v-model="tab.label" @blur="saveTabName(tab)" ref="tabInput" class="border p-1 rounded"/>
                <span v-else>{{ tab.label }}</span>
                <span v-else>{{ tab.label }}</span>
                <span @click.stop="closeTab(index)" class="ml-2 text-red-500 cursor-pointer">X</span>
            </div>
            <div @click="addTab" class="add-tab inline-flex flex-shrink-0 px-6 py-2 rounded-t-lg cursor-pointer bg-blue-500 text-white">
                +
            </div>
        </div>
    </div>
</template>

<script>
import {DocumentIcon, FolderIcon, FolderOpenIcon} from "@heroicons/vue/solid";
import {EventBus} from "../EventBus";
export default {
    props: ['tabs', 'activeTab'],

    data() {
        return {
            tabs: [
                { id: 1, label: 'Frame 1', content: 'MxGraphComponent', isEditing: false }
            ],
            nextTabId: 2,
            activeTab: 0
        };
    },
    methods: {
        changeTab(index) {
            this.activeTab = index;
            this.$emit('tabChanged', index);
        },
        addTab() {
            const nextTab = {
                id: this.nextTabId,
                label: `Frame ${this.nextTabId}`,
                content: 'MxGraphComponent',
                isEditing: false
            };
            this.tabs.push(nextTab);
            this.activeTab = this.tabs.length - 1;
            this.nextTabId++;
            this.$emit('tabAdded');
            EventBus.emit('add-frame', nextTab.label); // Enviar o nome do frame junto com o evento
        },
        enableEdit(tab) {
            tab.isEditing = true;
            this.$nextTick(() => {
                this.$refs.tabInput.focus();
            });
        },
        saveTabName(tab) {
            tab.isEditing = false;
        },
      closeTab(index) {
          this.tabs.splice(index, 1);
          if (this.activeTab >= index) {
            this.activeTab = Math.max(0, this.activeTab - 1);
          }
          EventBus.emit('tabClosed', index);
          this.$emit('tabChanged', this.activeTab);  // Adicione essa linha
      }
    }
}
</script>

<style scoped>
.tab {
    background-color: #E0E0E0;
}

.add-tab:hover {
    background-color: #2563EB;
}

.active-tab {
    background-color: #FFFFFF;
    border: 1px solid #D1D5DB;
    border-bottom: none;
}

.content {
    border-top: none;
}
</style>

// react-frontend/src/TabsComponent.js
import React, { useState, useRef, useEffect } from 'react';

const TabsComponent = ({ tabsProp, activeTabProp, onTabChanged, onTabAdded }) => {
  const [tabs, setTabs] = useState(tabsProp || []);
  const [activeTab, setActiveTab] = useState(activeTabProp || 0);
  const [nextTabId, setNextTabId] = useState(tabs.length + 1);
  const tabInputRef = useRef(null);

  useEffect(() => {
    if (tabs.length > 0) {
      setNextTabId(Math.max(...tabs.map(tab => tab.id)) + 1);
    }
  }, [tabs]);

  const changeTab = (index) => {
    setActiveTab(index);
    if (onTabChanged) {
      onTabChanged(index);
    }
  };

  const addTab = () => {
    const nextTab = {
      id: nextTabId,
      label: `Frame ${nextTabId}`,
      content: 'MxGraphComponent',
      isEditing: false
    };
    setTabs([...tabs, nextTab]);
    setActiveTab(tabs.length);
    setNextTabId(nextTabId + 1);
    if (onTabAdded) {
      onTabAdded(nextTab);
    }
    // Implementar EventBus.emit('add-frame', nextTab.label);
  };

  const enableEdit = (tab) => {
    const updatedTabs = tabs.map(t => {
      if (t.id === tab.id) {
        return { ...t, isEditing: true };
      }
      return t;
    });
    setTabs(updatedTabs);
  };

  const saveTabName = (tab) => {
    const updatedTabs = tabs.map(t => {
      if (t.id === tab.id) {
        return { ...t, isEditing: false };
      }
      return t;
    });
    setTabs(updatedTabs);
  };

  const closeTab = (index) => {
    const updatedTabs = [...tabs];
    updatedTabs.splice(index, 1);
    setTabs(updatedTabs);
    setActiveTab(Math.max(0, activeTab - 1));
    // Implementar EventBus.emit('tabClosed', index);
    if (onTabChanged) {
      onTabChanged(activeTab);
    }
  };

  return (
    <div className="tabs-container">
      <div className="tabs-wrapper">
        <div onClick={addTab} className="add-tab">+</div>
        {tabs.map((tab, index) => (
          <div key={tab.id} className={`tab ${activeTab === index ? 'active-tab' : ''}`}
               onClick={() => changeTab(index)}>
            {tab.isEditing ? (
              <input ref={tabInputRef} value={tab.label} onChange={(e) => saveTabName({ ...tab, label: e.target.value })} onBlur={() => saveTabName(tab)} className="tab-input" />
            ) : (
              <span>{tab.label}</span>
            )}
            <span onClick={(e) => { e.stopPropagation(); closeTab(index); }} className="close-btn">X</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default TabsComponent;
